# This is a basic workflow to help you get started with Actions

name: Archive-GitHub-Repo

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  GIT_ORG: 'octocat'
  GIT_REPO: 'Hello-World'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Archive-Repo :
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: Create Directory ${{ env.GIT_ORG }}_${{env.GIT_REPO}}
        id: archive_folder_id
        run: |
          foldername=${{ env.GIT_ORG }}_${{env.GIT_REPO}}_$(date +"%F-%H-%M-%S")
          echo "::set-output name=archive_folder_name::$foldername"
          mkdir $foldername

      - name: Create Directory Code and Metadata
        run: |
          cd ${{ steps.archive_folder_id.outputs.archive_folder_name }}
          mkdir Code
          mkdir Metadata

      - name: Take Repo backup
        run: |
          cd ${{ steps.archive_folder_id.outputs.archive_folder_name }}/Code
          git clone https://github.com/${{ env.GIT_ORG }}/${{env.GIT_REPO}}.git
          ls -ltra
          ls -ltra ${{env.GIT_REPO}}

      - name: Start Metadata backup
        run: |
          echo "starting metadata backup ..."
          ls -ltra
          ls -ltra ${{ steps.archive_folder_id.outputs.archive_folder_name }}
          ls -ltra ${{ steps.archive_folder_id.outputs.archive_folder_name }}/Code
          ls -ltra ${{ steps.archive_folder_id.outputs.archive_folder_name }}/Metadata

      # - name: Call Repo Api
      #   run: cd Metadata

      # - name: Call Pull Requests Api
      #   run: cd Metadata

      # - name: Call Issues Api
      #   run: cd Metadata

      # - name: Call Pull Requests Comments Api
      #   run: cd Metadata

      # - name: Call Pull Requests Requested Reviewers Api
      #   run: cd Metadata

      # - name: Call Issue Events Api
      #   run: cd Metadata

      # - name: Call Issue Comments Api
      #   run: cd Metadata

      # - name: Call Pull Requests Reviews Api
      #   run: cd Metadata

      # - name: Call Labels Api
      #   run: cd Metadata

      # - name: Call Milestones Api
      #   run: cd Metadata

      - name: Package the Archive
        run: |
          pwd
          ls -ltra
          zip -r ${{ steps.archive_folder_id.outputs.archive_folder_name }}.zip ${{ steps.archive_folder_id.outputs.archive_folder_name }}
          ls -ltra

      - name: Upload the Archive
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.archive_folder_id.outputs.archive_folder_name }}
          path: ./
          if-no-files-found: error