# This is a basic workflow to help you get started with Actions

name: Archive-GitHub-Repo

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs: 
      GIT_ORG:
        type: string
        required: true
        default: 'octocat'
      GIT_REPO:
        type: string
        required: true
        default: 'Hello-World'

# env:
#   GIT_ORG: 'octocat'
#   GIT_REPO: 'Hello-World'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Archive-Repo :
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: Create Directory ${{ github.event.inputs.GIT_ORG }}_${{github.event.inputs.GIT_REPO}}
        id: archive_folder_id
        run: |
          foldername=${{ github.event.inputs.GIT_ORG }}_${{github.event.inputs.GIT_REPO}}_$(date +"%F-%H-%M-%S")
          echo "::set-output name=archive_folder_name::$foldername"
          mkdir $foldername

      - name: Create Directory Code and Metadata
        run: |
          cd ${{ steps.archive_folder_id.outputs.archive_folder_name }}
          mkdir Code
          mkdir Metadata

      - name: Take Repo backup
        run: |
          cd ${{ steps.archive_folder_id.outputs.archive_folder_name }}/Code
          git clone https://github.com/${{ github.event.inputs.GIT_ORG }}/${{github.event.inputs.GIT_REPO}}.git
          ls -ltra
          ls -ltra ${{github.event.inputs.GIT_REPO}}

      - name: Start Metadata backup
        run: |
          echo "starting metadata backup ..."
          ls -ltra
          ls -ltra ${{ steps.archive_folder_id.outputs.archive_folder_name }}
          ls -ltra ${{ steps.archive_folder_id.outputs.archive_folder_name }}/Code
          ls -ltra ${{ steps.archive_folder_id.outputs.archive_folder_name }}/Metadata

      - name: Call Repo Api
        run: |
          cd ${{ steps.archive_folder_id.outputs.archive_folder_name }}/Metadata
          curl --location --request GET 'https://api.github.com/repos/${{ github.event.inputs.GIT_ORG }}/${{github.event.inputs.GIT_REPO}}' --header 'Content-Type: application/json' >> Repo.json
                   
      - name: Call Pull Requests Api
        run: |
          cd ${{ steps.archive_folder_id.outputs.archive_folder_name }}/Metadata
          curl --location --request GET 'https://api.github.com/repos/${{ github.event.inputs.GIT_ORG }}/${{github.event.inputs.GIT_REPO}}/pulls' --header 'Content-Type: application/json' >> PullRequests.json

      - name: Call Pull Requests Comments Api
        run: |
          cd ${{ steps.archive_folder_id.outputs.archive_folder_name }}/Metadata
          curl --location --request GET 'https://api.github.com/repos/${{ github.event.inputs.GIT_ORG }}/${{github.event.inputs.GIT_REPO}}/pulls/comments' --header 'Content-Type: application/json' >> PullRequestsComments.json

      - name: Call Issues Api
        run: |
          cd ${{ steps.archive_folder_id.outputs.archive_folder_name }}/Metadata
          curl --location --request GET 'https://api.github.com/repos/${{ github.event.inputs.GIT_ORG }}/${{github.event.inputs.GIT_REPO}}/issues' --header 'Content-Type: application/json' >> Issues.json

      - name: Call Issue Events Api
        run: |
          cd ${{ steps.archive_folder_id.outputs.archive_folder_name }}/Metadata
          curl --location --request GET 'https://api.github.com/repos/${{ github.event.inputs.GIT_ORG }}/${{github.event.inputs.GIT_REPO}}/issues/events' --header 'Content-Type: application/json' >> IssuesEvents.json

      - name: Call Issue Comments Api
        run: |
          cd ${{ steps.archive_folder_id.outputs.archive_folder_name }}/Metadata
          curl --location --request GET 'https://api.github.com/repos/${{ github.event.inputs.GIT_ORG }}/${{github.event.inputs.GIT_REPO}}/issues/comments' --header 'Content-Type: application/json' >> IssuesComments.json

      - name: Call Labels Api
        run: |
          cd ${{ steps.archive_folder_id.outputs.archive_folder_name }}/Metadata
          curl --location --request GET 'https://api.github.com/repos/${{ github.event.inputs.GIT_ORG }}/${{github.event.inputs.GIT_REPO}}/labels' --header 'Content-Type: application/json' >> Labels.json

      - name: Call Milestones Api
        run: |
          cd ${{ steps.archive_folder_id.outputs.archive_folder_name }}/Metadata
          curl --location --request GET 'https://api.github.com/repos/${{ github.event.inputs.GIT_ORG }}/${{github.event.inputs.GIT_REPO}}/milestones' --header 'Content-Type: application/json' >> Milestones.json

      - name: Package the Archive & Upload to archive.org
        run: |
          pwd
          ls -ltra
          zip -r ${{ steps.archive_folder_id.outputs.archive_folder_name }}.zip ${{ steps.archive_folder_id.outputs.archive_folder_name }}
          ls -ltra
          curl --location --header 'x-amz-auto-make-bucket:1' \
          --header 'x-archive-meta01-collection:opensource' \
          --header 'x-archive-meta-mediatype:Archives' \
          --header 'x-archive-meta-sponsor:GitHub Archival Utility' \
          --header 'x-archive-meta-language:eng' \
          --header "authorization: LOW WmX5sUovFoNm6XwN:MLP85d78R3bGIsPe" \
          --upload-file ${{ steps.archive_folder_id.outputs.archive_folder_name }}.zip \
          http://s3.us.archive.org/github-archives/${{ steps.archive_folder_id.outputs.archive_folder_name }}.zip

      - name: Upload the Archive
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.archive_folder_id.outputs.archive_folder_name }}
          path: ./${{ steps.archive_folder_id.outputs.archive_folder_name }}.zip
          if-no-files-found: error
