# This is a basic workflow to help you get started with Actions

name: Archive-GitHub-Repo

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  GIT_ORG: 'octocat'
  GIT_REPO: 'Hello-World'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Archive Repo :
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Runs a single command using the runners shell
      - name: Create Directory ${{ env.GIT_ORG }}_${{GIT_REPO}}
        run: |
          mkdir ${{ env.GIT_ORG }}_${{GIT_REPO}}_$now
          cd ${{ env.GIT_ORG }}_${{GIT_REPO}}_$now

      - name: Create Directory Code and Metadata
        run: |
          mkdir Code
          mkdir Metadata

      # Runs a single command using the runners shell
      - name: Take Repo backup
        run: |
          cd Code
          git clone https://github.com/${{ env.GIT_ORG }}/${{GIT_REPO}}.git
          ls -ltra
          cd ..

      # Runs a single command using the runners shell
      - name: Start Metadata backup
        run: cd Metadata


